### ISSUE TITLE
Questions about Example metabolites 

### ISSUE THREAD

**Issue by Peipenggang** [borenstein-lab/MIMOSA2shiny#18]
Dear Team,

I have been examining the sample metabolite data provided on your MIMOSA2shiny webpage (https://borenstein-lab.github.io/MIMOSA2shiny/input.html#). It has come to my attention that a majority of the values are negative. Could you elucidate why the ion intensities are presented as negative values? Is it a consequence of a normalization procedure? In addition, I am intrigued to know whether offering original ion intensities or relative  abundances would yield accurate prediction outcomes?

Furthermore, I am interested in understanding the potential implications of supplying Microbiome and Metabolics files, where the overall volume is relative abundance, on the ultimate result computations of the tool.

I would be grateful for any clarifications or resources that you could share pertaining to this matter.

Best regards,
Chris

**Comment by cnoecker** [comment]
Hi Chris, 
Thanks for your questions. Please see questions 1 and 4 in the "Input Data" section here: https://borenstein-lab.github.io/MIMOSA2shiny/faqs.html

We have done some experimentation with different normalization options for MIMOSA2, but we do not recommend any single normalization method. The example metabolite data is indeed data that has been previously scaled and normalized (and the small subset of the data included in the example just happened to have a lot of negative values). The effects of normalization likely depend on the community complexity and the specific methods used to generate the data. For metabolite data, I would normally recommend using the original ion intensities (or a scaled version of these), rather than relative abundances, which would then be subject to compositional effects. 

The only exception is that MIMOSA2 does normalized the stratified metagenomic abundance tables to average copy numbers for each feature, because it assumes that the input may be a table directly from Humann (which is only normalized by length and not library size). 

I hope that helps!
