### ISSUE TITLE
CMP scores transformation/normalization

### ISSUE THREAD

**Issue by aimirza** [borenstein-lab/MIMOSA2shiny#9]
Is there any further normalization or transformation of the CMP scores required if one would like to compare the CMP scores of each metabolite between two groups? In the original [paper ](https://microbialinformaticsj.biomedcentral.com/articles/10.1186/2042-5783-1-4#Sec2)for calculating Predicted Relative Metabolomic Turnover (PRMT), the scores were finally transformed by dividing the scores by the average for the parameter across all samples and then log-transformed (see equation below). Was this performed on the CMP scores or do the users have to transform the scores themselves? 

![image](https://user-images.githubusercontent.com/17455613/113073113-52249200-917d-11eb-878d-9736a5c972db.png)

**Comment by cnoecker** [comment]
Hi Ali, 
MIMOSA2 does not transform the scores for a few reasons. First, our evaluation of typical distributions of CMP scores did not suggest that log transformation would be indicated. Second, because the default MIMOSA workflow uses a robust rank-based regression method to compare with metabolite data, scaling and transforming the scores has little to no effect on the results. This also preserves the additive nature of CMP scores across taxa (for stratified datasets), which facilitates calculating their contributions to metabolite variation. Hope this helps.

**Comment by cnoecker** [comment]
You can read more about our modification of the PRMT method in the first MIMOSA paper: https://msystems.asm.org/content/1/1/e00013-15.full . The MIMOSA2 manuscript also includes more methodological details and will hopefully be online as a preprint very soon.

**Comment by aimirza** [comment]
For the robust rank-based regression method, are you referring to the R package `mblm`? Looking forward to reading the new manuscript!

**Comment by aimirza** [comment]
My mistake, the PRMT method paper does not post-normalize or transform the PRMT values. I misread the paper! That equation I originally referenced was to normalize _other_ microbiome features to correlate with PRMT scores, not to normalize PRMT scores themselves.

**Comment by cnoecker** [comment]
Hi Ali,
MIMOSA2 uses the Rfit package for rank-based regression. And sorry, yes, we tested log-transforming the magnitude of the CMP scores (while keeping the sign intact), and did not find any reason to do so. We found that log transforming metabolite values may be appropriate for some datasets, and that is included as an option in the analysis.
